---
name: Merge Release Hotfix
description: |
  Automatically prepare your release hotfixes for merge back into your development branch.
 

author: "airtonix"
inputs:
  GithubToken:
    required: true
    description: "auth token"
  TargetRefs:
    required: true
    description: comma separated list of target refs
  SourceRef:
    required: true
    description: where to create branch from to merge into sorucerefs
  PrBranchNameTemplate:
    required: false
    description: "template used to populate the branch name"
    default: "merge-hotfix/{{source}}-to-{{target}}"
  PrTitleTemlate:
    required: false
    description: "template used to populate the PR title"
    default: "merge-hotfix: {{source}}"
  PrBodyTemplate:
    required: false
    description: "template used to populate the PR body"
    default: "merge hotfixes from {{source}} to {{target}}"

runs:
  using: "node16"
  main: "dist/index.js"
